accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/profile/', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/',views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('', views.index, name='index'),
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   title = models.CharField(max_length=10)
   content = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)
   
   def __str__(self):
       return self.title
       
class Comment(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   board = models.ForeignKey(Board , on_delete=models.CASCADE)
   content = models.CharField(max_length=140)
   
   def __str__(self):
      return self.content

boards/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Board, Comment


# class BoardForm(forms.Form):
#     title = forms.CharField(label="제목", widget=forms.TextInput(attrs={
#                                                         'placeholder': 'THE TITLE!',
#                                              }))
#     content =  forms.CharField(label="내용", 
#                               error_messages={'required': '내용을 입력해주세요!'},
#                               widget=forms.Textarea(attrs={
#                                                         'class': 'Content-input',
#                                                         'rows': 5,
#                                                         'cols': 50,
#                                                         'placeholder': 'Fill the Content~'
#                                              }))

# 더 짧게!
class BoardForm(forms.ModelForm):
    # Model의 정보를 작성하는 곳
    class Meta:
        model = Board
        # models.py에 지정해놓은 필드를 사용한다.
        fields = ['title', 'content',]
        widgets = {'title': forms.TextInput(attrs={
                                                'placeholder':'제목을 입력하세요.',
                                                'class': 'title'}),
                  'content': forms.Textarea(attrs={
                                                'placeholder':'내용을 입력하세요.',
                                                'class': 'content',
                                                'rows': 5,
                                                'cols': 50,})
                }
        error_messages = {
                          'title': {'required': '입력하시라고요.'},
                          'content': {'required': '입력 하.시.라.고.요.'}
                          }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', '작성!'))
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# import hashlib
from .models import Board, Comment
from .forms import BoardForm, CommentForm

# Create your views here.
def index(request):
    # if request.user.is_authenticated:
    #     gravatar_url = hashlib.md5(request.user.email.strip().lower().encode('utf-8')).hexdigest()
    # else:
    #     gravatar_url = None
    
    # 가져올 리스트가 없으면 404 페이지를 불러옴.
    boards = get_list_or_404(Board.objects.order_by('-pk'))
    # boards = Board.objects.order_by('-pk')
    
    context = {
        'boards': boards,
        #'gravatar_url': gravatar_url,
    }
    return render(request, 'boards/index.html', context)

@login_required
def create(request):
    # POST 요청이면 FORM 데이터를 처리한다.
    if request.method == 'POST':
        # 이 처리과정은 'binding'으로 불리는데, 폼의 유효성 체크를 할 수 있도록 해준다.
        form = BoardForm(request.POST)
        if form.is_valid():
            # form 유효성 체크(안전한 데이터인지, 요구하는 글자수가 맞는지)
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # 검증을 통과한 깨끗한 데이터를 form에서 가져와서 board를 만든다.
            # board = Board.objects.create(title=title, content=content)
            board = form.save(commit=False) 
            # board를 바로 저장하지 않고, 현재 유저를 넣고 저장
            # 실제 db에 반영 전까지의 단계를 진행하고, 그 중간에 user 정보를 request.user에서 가져와서 그 후에 저장한다.
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.pk)
    # GET 요청(혹은 다른 메서드)이면 기본 폼을 생성한다.
    else:
        form = BoardForm()
    context = {'form': form,}
    return render(request, 'boards/form.html', context)

def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    # comments = board.comment_set.all()
    comment_form = CommentForm()
    context = {
        'board': board,
        # 'comments':comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)
    
def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            board.delete()
            return redirect('boards:index')
        else:
            return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:index')

@login_required
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board) # 1
            if form.is_valid():
                board = form.save() # 2
                return redirect('boards:detail', board.pk)
        # GET 요청이면(수정하기 버튼을 눌렀을 때.)
        else:
            # BoardForm을 초기화(사용자 입력 값을 넣어준 상태로)
            form = BoardForm(instance=board) # 3
            # initial={'title':board.title, 'content': board.content} 라고도 쓸 수 있음. 하지만 길어진다.
            # initial=board.__dict__는 딕셔너리 전체를 받는다.
         
        # 1. POST : 요청에서 검증에 실패하였을 때, 오류 메세지가 포함된 상태.
        # 2. GET : 요청에서 초기화된 상태.
    else:
        return redirect('boards:index')
    context = {'form': form,
        'board': board,
    }
    return render(request, 'boards/form.html', context)

@require_POST
@login_required
def comment_create(request, board_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.board_id = board_pk
        comment.save()
    return redirect('boards:detail', board_pk)
    
    # board = get_object_or_404(Board, pk=board_pk)
    # if request.method == 'POST':  # require_POST를 import하면 이 과정이 필요 없어짐.
    #     form = CommentForm(request.POST)
    #     if form.is_valid():
    #         content = request.POST.get('content')
    #         comment = Comment(board=board, content=content)
    #         comment.save()
    #         return redirect('boards:detail', board.pk)
    # else:
    #     form = CommentForm()
    # context = {'form': form,}
    # return render(request, 'boards/form.html', context)

@require_POST
@login_required
def comment_delete(request, board_pk, comment_pk):
    # comment = Comment.objects.get(pk=comment_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    # if comment.user == request.user:
    comment.delete()
    return redirect('boards:detail', board_pk)
    # else:
    #     return redirect('boards:detail', board_pk)

boards/templates/boards/base.html
{% load gravatar %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Document</title>
    <style>
    @import url('https://fonts.googleapis.com/css?family=Do+Hyeon|Gaegu|Nanum+Myeongjo|Yeon+Sung');
    </style>
</head>

<body>
    <div class="container mt-3">
        {% if user.is_authenticated %}
        <div class="container d-flex align-self-center" style="font-family: 'Yeon Sung', cursive;">
            <h1 style="display: inline">
                <img class="rounded-circle" src="https://s.gravatar.com/avatar/{{ user.email | makemd5 }}?s=80" alt="profile img"></img>
                안녕하세요, {{ user.username }}님
            </h1>
            <!--<p>안녕, {{ user.username }}</p>-->
            <div class="btn-group mt-3 mx-3" style="display: inline">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                설정
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'accounts:profile' user.id %}">프로필 조회</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
              </div>
            </div>
        </div>
        {% else %}
        
        <!--<h1>-->
        <!--    <a href="{# url 'accounts:login' #}">[로그인]</a>-->
        <!--    <a href="{# url 'accounts:signup' #}">[회원가입]</a>-->
        <!--</h1>-->
        <div class="btn-group" role="group" aria-label="Basic example">
            <h1>
            <a type="button" class="btn btn-warning" href="{% url 'accounts:login' %}">로그인</a>
            <a type="button" class="btn btn-warning" href="{% url 'accounts:signup' %}">회원가입</a>
            </h1>
        </div>
        {% endif %}
        
        <hr>
        
    {% block body %} {% endblock %}
    </div>
    
    <!--고양이-->
    <!--<div class="div" style="position:absolute; right:0; top:0;">-->
    <!--<marquee direction="up"  height="300" behavior="alternate">-->
    <!--    <marquee behavior="alternate" >-->
    <!--        <img src="https://media.giphy.com/media/Kebxw7tA8HgiileQFX/giphy.gif"></img>-->
    <!--    </marquee>-->
    <!--</marquee>-->
    <!--</div>-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>

</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %} {% block body %}
{% load crispy_forms_tags %}
<h4 style="font-family: 'Yeon Sung', cursive;">{{ board.pk }}번째 글</h4>
<h1 style="font-family: 'Yeon Sung', cursive;">{{ board.title }}</h1>
<p class="d-flex justify-content-end" style="font-family: 'Yeon Sung', cursive;"><b>작성자 {{ board.user }}</b></p>
<hr>
<h4 style="font-family: 'Yeon Sung', cursive;">{{ board.content }}</h4>
<hr>

<div class="d-flex justify-content-end">
    <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{% url 'boards:index' %}" type="button" class="btn btn-primary">[뒤로가기]</a>
        {% if user == board.user %}
            <a href="{% url 'boards:update' board.pk %}" type="button" class="btn btn-primary">[수정]</a> 
            <form  action="{% url 'boards:delete' board.pk %}" style='display:inline' method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제" />
            </form>
        {% endif %}
    </div>
</div>
<hr> 


<!--코멘트 보여주기-->
{% for comment in board.comment_set.all %}
<!--{# for comment in comments #}-->
<div>
    <b>{{ comment.user }}</b> : {{ comment.content }}
    
    {% if user == comment.user %}
    <form action="{% url 'boards:comment_delete' board.pk comment.pk %}" method="post" style='display:inline' onsubmit="return confirm('R U SURE?');">
        {% csrf_token %}
        <input type='submit' value='삭제' />
    </form>
    {% endif %}
</div>
{% empty %}
<p><b>댓글이 없어요...</b></p>
{% endfor %}
<hr>

<!--코맨트 달기-->
<p>댓글 작성 / {{ board.comment_set.all | length }}</p>

{% if user.is_authenticated %}
<form action="{% url 'boards:comment_create' board.pk %}" method='POST'>
    {% csrf_token %} 
    {{ comment_form|crispy }}
    <input type="submit" name="submit" />
</form>
{% else %}
<p>로그인 하셔야 댓글을 달 수 있습니다.<a href="{% url 'accounts:login' %}">[로그인하기]</a></p>
{% endif %}


{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>NEW board</h1>
{% else %}
    <h1>EDIT board</h1>
{% endif %}

<!--1 form-->
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <!--as_p/as_ul/as_table-->
    <input type="submit" value="Submit"/>
</form>
<br>
<!--2 form-->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    {{ form.title }}-->
<!--    {{ form.content }}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>    -->
<br>
<!--3 form-->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    {# for field in form #}-->
<!--        {{ field.errors }}-->
<!--        {{ field.label_tag }} {{ field }}-->
<!--    {# endfor #}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>  -->
<!--<br>-->
<!--4 form-->
<!--{{ form.non_field_errors }}-->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    <div>-->
<!--        {{ form.title.errors }}-->
<!--        {{ form.title.label_tag }}-->
<!--        {{ form.title }}-->
<!--    </div>-->
<!--    <div>-->
<!--        {{ form.content.errors }}-->
<!--        {{ form.content.label_tag }}-->
<!--        {{ form.content }}-->
<!--    </div>-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->
<!--5 form-->
<!--{# crispy form #}-->


{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}">[BACK]</a>
{% else %}
    <a href="{% url 'boards:detail' board.pk %}">[BACK]</a>
{% endif %}

{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %} 
<h1 style="font-family: 'Do Hyeon', sans-serif;">게시글 목록</h1>
{% if user.is_authenticated %}
    <a href="{% url 'boards:create' %}">[새 글 작성]</a>
{% else %}
    <a href="{% url 'accounts:login' %}">새 글을 작성하려면 로그인 하세요.</a>
{% endif %}
<hr>

{% for board in boards %}
    <p>{{ board.pk }}</p>
    <p><b>작성자 <a href="{% url 'accounts:profile' board.user_id %}">{{ board.user }}</a></b></p>
    <h4 style="font-family: 'Yeon Sung', cursive;">{{ board.title }}</h4>
    <a href="{% url 'boards:detail' board.pk %}" style="font-family: 'Yeon Sung', cursive;">[글 보러가기]</a>
    <hr>
{% endfor %}
{% endblock %}