accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/profile/', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/',views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('', views.index, name='index'),
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   title = models.CharField(max_length=10)
   content = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)
   
   def __str__(self):
       return self.title
       
class Comment(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   board = models.ForeignKey(Board , on_delete=models.CASCADE)
   content = models.CharField(max_length=140)
   
   def __str__(self):
      return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'email',]

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm #UserChangeForm #UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash # 비번 변경 시에도 로그인 유지
from django.contrib.auth import get_user_model as User
from django.contrib.auth.decorators import login_required
from .forms import UserCustomChangeForm, UserCustomCreationForm


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
        
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()         #1
            auth_login(request, user)  #2
            return redirect('boards:index')
    else:
        form = UserCustomCreationForm()
    context = {'form':form}
    return render(request, 'accounts/auth_form.html', context)
    
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.POST.get('next') or 'boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
        'next': request.GET.get('next',''),
    }
    return render(request, 'accounts/login.html', context)
        
def logout(request):
    auth_logout(request)
    return redirect('boards:index')
    
def delete(request):
    user = request.user
    if request.method == "POST":
        # DELETE
        user.delete()
    return redirect('boards:index')
    
def edit(request):
    if request.method == 'POST':
        # 수정 로직 진행
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    context = {'form': form,}
    return render(request, 'accounts/auth_form.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST) # 인자 순서 유의
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) # 현재 유저가 로그아웃 되는 것을 막음
            return redirect('boards:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form}
    return render(request, 'accounts/auth_form.html', context)
    
def profile(request, user_pk):
    """
    1. 내가 쓴 모든 글 출력
    2. 내가 쓴 댓글들 출력
    3. 작성자를 눌렀을때 프로필로 이동
    """
    user = get_object_or_404(User(), pk=user_pk)
    ctx = {
        'profile_user': user,
    }
    return render(request, 'accounts/profile.html', ctx)

accounts/templates/accounts/auth_form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'edit' %}
<h1>회원정보수정</h1>
{% else %}
<h1>비밀번호변경</h1>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Document</title>
    <style>
    @import url('https://fonts.googleapis.com/css?family=Do+Hyeon|Gaegu|Nanum+Myeongjo|Yeon+Sung');
    </style>
</head>

<body>
    <div class="container">
        {% block body %}{% endblock %}
    </div>

    <!--고양이-->
    <!--<div class="div" style="position:absolute; right:0; top:0;">-->
    <!--<marquee direction="up"  height="300" behavior="alternate">-->
    <!--    <marquee behavior="alternate" >-->
    <!--        <img src="https://media.giphy.com/media/Kebxw7tA8HgiileQFX/giphy.gif"></img>-->
    <!--    </marquee>-->
    <!--</marquee>-->
    <!--</div>-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/accounts/change_password.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>비빌번호 변경</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원정보수정</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
    <input type="hidden" value="{{ next }}" name="next"/>
</form>
<a href="{% url 'accounts:signup' %}">[회원가입하기]</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %} 
{% block body %} 

{% load gravatar %}
<div class="container d-flex mt-5">
    <!--프로필 이미지-->
    <div class="mx-5">
        <img src="https://s.gravatar.com/avatar/{{ profile_user.email|makemd5 }}?s=150" class="rounded-circle" alt="profile" />
    </div>
    <!--프로필 유저 이름-->
    <div class="mt-3">
        <div class="container">
            <div class="row">
                <h1 style="font-family: 'Yeon Sung', cursive;">{{ profile_user.username }}</h1>
                
                {% if user == profile_user %}
    <!--설정-->
                <div class="btn-group mt-2 mx-5" style="display: inline">
                  <button type="button" class="btn btn-warning dropdown-toggle" style="font-family: 'Yeon Sung', cursive;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    설정
                  </button>
                  <div class="dropdown-menu" style="font-family: 'Yeon Sung', cursive;">
                    <a class="dropdown-item" href="{% url 'accounts:edit' %}">[회원정보수정]</a>
                    <a class="dropdown-item" href="{% url 'accounts:change_password' %}">[비밀번호 변경]</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">[로그아웃]</a>
                    <div class="dropdown-divider"></div>
                    <form class="dropdown-item" action="{% url 'accounts:delete' %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??');">
                        {% csrf_token %}
                        <input type="submit" value="회원탈퇴" />
                    </form>
                  </div>
                </div>
                
                {% endif %}
            </div>
        </div>   
        
    <!--이메일 정보-->
        <h4 style="font-family: 'Yeon Sung', cursive;">E-mail 주소 : {{ profile_user.email }}</h4>
    <!--게시글 수, 댓글 수-->
    <h5 style="font-family: 'Yeon Sung', cursive;">게시글 수 : {{ profile_user.board_set.all | length }},  댓글 수 : {{ profile_user.comment_set.all | length }}</h5>
    </div>
    <hr>
</div>
<br>
<br>

<!--글 목록-->
<h2 style="font-family: 'Nanum Myeongjo', serif;"><b>{{ profile_user.username }}의 글목록</b></h2>
<br>
<div class="container" style="font-family: 'Yeon Sung', cursive;">
    <div class="row">
{% for board in profile_user.board_set.all %}
        <div class="card col-4" style="width: 18rem;">
            <img src="http://t1.daumcdn.net/liveboard/petxlab/a599fae28cfa423baecba6e1ffb24674.gif" class="card-img-top mt-3" alt="cat">
            <div class="card-body">
                <h3 class="card-title">제목 : <b>{{ board.title }}</b></h3>
                <h5 class="card-text">내용 : {{ board.content }}</h5>
                <p>달린 댓글 수 : {{ board.comment_set.count }}</p>
                <a href="{% url 'boards:detail' board.id %}" class="card-link">[글 보러가기]</a>
            </div>
        </div>
{% endfor %}
    </div>
</div>

<!--{# for board in profile_user.board_set.all #}-->
<!--    <p>제목 : <a href="{# url 'boards:detail' board.id #}">{{ board.title }}</a></p>-->
<!--    <p>내용 : {{ board.content }}</p>-->
<!--    <p>달린 댓글 수 : {{ board.comment_set.count }}</p>-->
<!--    <hr> -->
<!--{# endfor #}-->
<br>
<br>


<!--댓글 목록-->
<h2 style="font-family: 'Nanum Myeongjo', serif;"><b>{{ profile_user.username }}의 댓글목록</b></h2>
<br>
{% for comment in profile_user.comment_set.all %}
    <h4 style="font-family: 'Yeon Sung', cursive;">[<a href="{% url 'boards:detail' comment.board.id %}">'{{ comment.board }}'</a>글의 댓글] : {{ comment.content }}</h4>
    <hr> 
{% endfor %}

<div class="d-flex justify-content-end">
    <a href="{% url 'boards:index' %}" type="button" class="btn btn-primary">[뒤로가기]</a>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원가입</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>

{% endblock %}